import { ApiOperationOptions } from '@nestjs/swagger';

export const ThesisModeratorDocs = {
	publishTheses: {
		summary: 'Publish theses for student selection',
		description: `Publish or unpublish a batch of thesis projects, making them available or unavailable for student selection.\n\n- **Authorization:** Moderator only.\n- **Validations:**\n  - All thesis IDs must exist.\n  - Only approved theses can be published.\n  - Each thesis must have exactly 2 supervisors to be published.\n  - Cannot unpublish theses already selected by groups.\n- **Business logic:**\n  - Updates publication status for each thesis.\n  - Checks supervisor count for each thesis before publishing.\n  - Sends notification emails to lecturers.\n  - Triggers cache invalidation.\n- **Error handling:**\n  - 404 if thesis not found.\n  - 409 if not approved, does not have 2 supervisors, already published/unpublished, or selected by group.\n- **Logging:** Logs all publish/unpublish attempts, notifications, and errors.\n\n**Status Codes:**\n- **200 OK:** Theses successfully published/unpublished\n- **400 Bad Request:** Invalid input data or missing thesis IDs\n- **401 Unauthorized:** Invalid or missing authentication token\n- **403 Forbidden:** User does not have moderator role\n- **404 Not Found:** One or more thesis IDs do not exist\n- **409 Conflict:** Theses not approved, missing supervisors, already in target state, or selected by groups\n- **500 Internal Server Error:** Database or server error`,
	} as ApiOperationOptions,

	reviewThesis: {
		summary: 'Review and approve/reject thesis',
		description: `Conduct administrative review of a submitted thesis project, with approval or rejection.\n\n- **Authorization:** Moderator only.\n- **Validations:**\n  - Thesis must be in Pending status and not published.\n  - Only Approved or Rejected status allowed.\n- **Business logic:**\n  - Updates thesis status and sends notification email.\n  - Triggers cache invalidation.\n- **Error handling:**\n  - 404 if thesis not found.\n  - 409 if already published or invalid status.\n- **Logging:** Logs all review attempts, notifications, and errors.\n\n**Status Codes:**\n- **200 OK:** Thesis successfully reviewed and status updated\n- **400 Bad Request:** Invalid input data or status value\n- **401 Unauthorized:** Invalid or missing authentication token\n- **403 Forbidden:** User does not have moderator role\n- **404 Not Found:** Thesis does not exist\n- **409 Conflict:** Thesis is published or not in Pending status\n- **500 Internal Server Error:** Database or server error`,
	} as ApiOperationOptions,

	assignThesis: {
		summary: 'Assign thesis to group',
		description: `Assign a thesis project to a specific student group.\n\n- **Authorization:** Moderator only.\n- **Validations:**\n  - Thesis must be approved and published.\n  - Group must exist, be in the same semester, and not already have a thesis.\n  - Thesis must not already be assigned.\n- **Business logic:**\n  - Assigns thesis to group and updates records.\n  - Triggers cache invalidation and sends notification emails.\n- **Error handling:**\n  - 404 if thesis or group not found.\n  - 409 if already assigned, not approved/published, or group already has thesis.\n- **Logging:** Logs all assignment attempts, notifications, and errors.\n\n**Status Codes:**\n- **200 OK:** Thesis successfully assigned to group\n- **400 Bad Request:** Invalid input data or missing group ID\n- **401 Unauthorized:** Invalid or missing authentication token\n- **403 Forbidden:** User does not have moderator role\n- **404 Not Found:** Thesis or group does not exist\n- **409 Conflict:** Thesis already assigned, not approved/published, group already has thesis, or semester mismatch\n- **500 Internal Server Error:** Database or server error`,
	} as ApiOperationOptions,
};
