export enum EmailJobType {
	SEND_GROUP_LEADER_CHANGE_NOTIFICATION = 'send-group-leader-change-notification',
	SEND_GROUP_MEMBER_CHANGE_NOTIFICATION = 'send-group-member-change-notification',
	SEND_GROUP_DELETION_NOTIFICATION = 'send-group-deletion-notification',
	SEND_INVITE_REQUEST_NOTIFICATION = 'send-invite-request-notification',
	SEND_JOIN_REQUEST_NOTIFICATION = 'send-join-request-notification',
	SEND_LECTURER_ACCOUNT = 'send-lecturer-account',
	SEND_NOTIFICATION = 'send-notification',
	SEND_OTP = 'send-otp',
	SEND_REQUEST_STATUS_UPDATE = 'send-request-status-update',
	SEND_RESET_PASSWORD = 'send-reset-password',
	SEND_REVIEWER_ASSIGNMENT_NOTIFICATION = 'send-reviewer-assignment-notification',
	SEND_REVIEW_COMPLETED_NOTIFICATION = 'send-review-completed-notification',
	SEND_SEMESTER_ONGOING_NOTIFICATION = 'send-semester-ongoing-notification',
	SEND_STUDENT_ACCOUNT = 'send-student-account',
	SEND_SUPERVISION_NOTIFICATION = 'send-supervision-notification',
	SEND_THESIS_STATUS_CHANGE = 'send-thesis-status-change',
	SEND_THESIS_ASSIGNMENT_NOTIFICATION = 'send-thesis-assignment-notification',
	SEND_ENROLLMENT_RESULT_NOTIFICATION = 'send-enrollment-result-notification',
}
