import { ApiOperationOptions } from '@nestjs/swagger';

export const AIStudentDocs = {
	suggestStudentsForGroup: {
		summary: 'Suggest students for a group using AI',
		description: `Get AI-powered suggestions for students that would be a good fit for the specified group.\n\n- **Authenticated access** (requires JWT authentication).\n- Analyzes group requirements, skills, responsibilities, and thesis content.\n- Uses vector similarity search to find compatible students.\n- Returns top 10 student suggestions by default with compatibility scores.\n- Considers skill matching, responsibility alignment, and thesis content relevance.\n- Excludes students already in the group.\n\n**Parameters:**\n- \`groupId\`: Required - UUID of the group to suggest students for.\n\n**Response includes:**\n- List of suggested students with compatibility scores\n- Student information (code, name, skills, responsibilities)\n- Matching criteria details\n- Compatibility breakdown (skills, responsibilities, thesis alignment)\n\n**Algorithm factors:**\n- Skill matching (40% weight): Compares student skills with group requirements\n- Responsibility matching (30% weight): Aligns student roles with group expectations\n- Base compatibility (30% weight): General enrollment and qualification criteria\n\n**Use cases:**\n- Group formation assistance\n- Student-project matching\n- Skill gap identification\n- Balanced team composition\n- Academic collaboration enhancement`,
	} as ApiOperationOptions,

	suggestGroupsForStudent: {
		summary: 'Suggest groups for a student using AI',
		description: `Get AI-powered suggestions for groups that would be a good fit for the specified student.\n\n- **Authenticated access** (requires JWT authentication).\n- Analyzes student skills, responsibilities, and interests.\n- Uses compatibility scoring to find suitable groups.\n- Returns top 10 group suggestions by default with compatibility scores.\n- Only suggests groups with less than 5 members.\n- Excludes groups the student is already a member of.\n- Filters groups by the specified semester.\n\n**Request Body:**\n- \`studentId\`: Required - UUID of the student to suggest groups for.\n- \`semesterId\`: Required - UUID of the semester to find groups in.\n\n**Response includes:**\n- List of suggested groups with compatibility scores\n- Group information (code, name, project direction, thesis)\n- Current members count and member list (only groups with <5 members)\n- Matching criteria details (skills, responsibilities)\n\n**Algorithm factors:**\n- Skill alignment: How well student skills match group requirements\n- Responsibility fit: Alignment between student expectations and group needs\n- Group availability: Only groups with available member slots (less than 5 members)\n- Semester filtering: Only groups in the specified semester\n- Project compatibility: Relevance to student interests and thesis content\n\n**Use cases:**\n- Student group selection assistance within a semester\n- Project matching for students\n- Academic team formation\n- Skill-based group recommendations\n- Collaborative learning enhancement`,
	} as ApiOperationOptions,

	getStudentGroupCompatibility: {
		summary: 'Analyze student-group compatibility using AI',
		description: `Get detailed compatibility analysis between a specific student and group.\n\n- **Authenticated access** (requires JWT authentication).\n- Provides comprehensive compatibility scoring and analysis.\n- Breaks down compatibility factors with detailed scores.\n- Analyzes skill alignment, responsibility matching, and thesis relevance.\n- Helps in making informed decisions about student-group assignments.\n\n**Parameters:**\n- \`studentId\`: Required - UUID of the student to analyze.\n- \`groupId\`: Required - UUID of the group to analyze compatibility with.\n\n**Response includes:**\n- Overall compatibility score (0-100)\n- Detailed breakdown of matching factors\n- Skill match analysis with specific skills and levels\n- Responsibility alignment details\n- Thesis content relevance assessment\n- Recommendations and potential areas of concern\n\n**Scoring methodology:**\n- Weighted algorithm considering multiple factors\n- Skill level proficiency analysis\n- Binary responsibility matching\n- Semantic similarity for thesis content\n- Contextual group dynamics consideration\n\n**Use cases:**\n- Individual student assessment\n- Group composition optimization\n- Academic advisor guidance\n- Student placement decisions\n- Performance prediction`,
	} as ApiOperationOptions,
};
