import { ApiOperationOptions } from '@nestjs/swagger';

export const AIStudentDocs = {
	suggestStudentsForGroup: {
		summary: 'Suggest students for a group using AI',
		description: `Get AI-powered suggestions for students that would be a good fit for the specified group based on responsibility balance and team synergy.\n\n- **Authenticated access** (requires JWT authentication).\n- Analyzes current group members' responsibility levels and identifies skill gaps.\n- Uses Gemini AI to evaluate candidate students based on complementary skills.\n- Returns suggested students with compatibility scores and detailed reasoning.\n- Only suggests students enrolled in the semester but not in any group.\n- Automatically determines semester from the group.\n\n**Parameters:**\n- \`groupId\`: Required - UUID of the group to suggest students for.\n\n**Response includes:**\n- \`reasons\`: AI-generated explanation of why these students were selected and what skills the group needs\n- \`students\`: Array of student objects with all student details PLUS compatibility scores (0.0-1.0)\n- Each student object contains: full profile, responsibilities, major, enrollments, AND compatibility score\n- Students are sorted by compatibility score from highest to lowest\n\n**Student Response Structure:**\nEach student in the response contains all standard student details plus:\n- \`compatibility\`: Number (0.0-1.0) indicating how well the student fits the group\n- All other StudentDetailResponse fields (id, fullName, studentCode, major, etc.)\n\n**Responsibility System:**\n- Each student has 5 responsibilities: Backend, Frontend, DevOps, BA (Business Analyst), and AI\n- Each responsibility has a level from 0 to 5 (0 = no experience, 5 = expert level)\n- Forms a radar chart-like skill profile for each student\n\n**AI Algorithm factors:**\n- **Skill Gap Analysis**: Identifies missing or weak areas in the current group\n- **Complementary Skills**: Prefers candidates who strengthen weak areas\n- **Balanced Distribution**: Avoids overloading one area while neglecting others\n- **Team Synergy**: Considers overall fit with existing members\n- **Compatibility Scoring**: 0.0-1.0 scale with detailed criteria\n\n**Compatibility Scoring:**\n- 0.9-1.0: Excellent fit, fills critical gaps perfectly\n- 0.7-0.8: Very good fit, strengthens team significantly\n- 0.5-0.6: Good fit, provides solid contribution\n- 0.3-0.4: Fair fit, some benefits but limitations\n- 0.0-0.2: Poor fit, doesn't address team needs\n\n**Use cases:**\n- Group formation assistance for academic projects\n- Skill gap identification and filling\n- Balanced team composition optimization\n- Academic collaboration enhancement\n- Project team building with complementary skills`,
	} as ApiOperationOptions,

	suggestGroupsForStudent: {
		summary: 'Suggest groups for a student using AI',
		description: `Get AI-powered suggestions for groups that would be a good fit for the specified student.\n\n- **Authenticated access** (requires JWT authentication).\n- Analyzes student skills, responsibilities, and interests.\n- Uses compatibility scoring to find suitable groups.\n- Returns top 10 group suggestions by default with compatibility scores.\n- Only suggests groups with less than 5 members.\n- Excludes groups the student is already a member of.\n- Filters groups by the specified semester.\n\n**Request Body:**\n- \`studentId\`: Required - UUID of the student to suggest groups for.\n- \`semesterId\`: Required - UUID of the semester to find groups in.\n\n**Response includes:**\n- List of suggested groups with compatibility scores\n- Group information (code, name, project direction, thesis)\n- Current members count and member list (only groups with <5 members)\n- Matching criteria details (skills, responsibilities)\n\n**Algorithm factors:**\n- Skill alignment: How well student skills match group requirements\n- Responsibility fit: Alignment between student expectations and group needs\n- Group availability: Only groups with available member slots (less than 5 members)\n- Semester filtering: Only groups in the specified semester\n- Project compatibility: Relevance to student interests and thesis content\n\n**Use cases:**\n- Student group selection assistance within a semester\n- Project matching for students\n- Academic team formation\n- Skill-based group recommendations\n- Collaborative learning enhancement`,
	} as ApiOperationOptions,
};
