import { ApiOperationOptions } from '@nestjs/swagger';

export const AIStudentDocs = {
	suggestStudentsForGroup: {
		summary: 'Suggest students for a group using AI',
		description: `Get AI-powered suggestions for students that would be a good fit for the specified group.\n\n- **Authenticated access** (requires JWT authentication).\n- Analyzes group requirements, skills, responsibilities, and thesis content.\n- Uses vector similarity search to find compatible students.\n- Returns top 10 student suggestions by default with compatibility scores.\n- Considers skill matching, responsibility alignment, and thesis content relevance.\n- Excludes students already in the group.\n\n**Parameters:**\n- \`groupId\`: Required - UUID of the group to suggest students for.\n\n**Response includes:**\n- List of suggested students with compatibility scores\n- Student information (code, name, skills, responsibilities)\n- Matching criteria details\n- Compatibility breakdown (skills, responsibilities, thesis alignment)\n\n**Algorithm factors:**\n- Skill matching (40% weight): Compares student skills with group requirements\n- Responsibility matching (30% weight): Aligns student roles with group expectations\n- Base compatibility (30% weight): General enrollment and qualification criteria\n\n**Use cases:**\n- Group formation assistance\n- Student-project matching\n- Skill gap identification\n- Balanced team composition\n- Academic collaboration enhancement`,
	} as ApiOperationOptions,

	getStudentGroupCompatibility: {
		summary: 'Analyze student-group compatibility using AI',
		description: `Get detailed compatibility analysis between a specific student and group.\n\n- **Authenticated access** (requires JWT authentication).\n- Provides comprehensive compatibility scoring and analysis.\n- Breaks down compatibility factors with detailed scores.\n- Analyzes skill alignment, responsibility matching, and thesis relevance.\n- Helps in making informed decisions about student-group assignments.\n\n**Parameters:**\n- \`studentId\`: Required - UUID of the student to analyze.\n- \`groupId\`: Required - UUID of the group to analyze compatibility with.\n\n**Response includes:**\n- Overall compatibility score (0-100)\n- Detailed breakdown of matching factors\n- Skill match analysis with specific skills and levels\n- Responsibility alignment details\n- Thesis content relevance assessment\n- Recommendations and potential areas of concern\n\n**Scoring methodology:**\n- Weighted algorithm considering multiple factors\n- Skill level proficiency analysis\n- Binary responsibility matching\n- Semantic similarity for thesis content\n- Contextual group dynamics consideration\n\n**Use cases:**\n- Individual student assessment\n- Group composition optimization\n- Academic advisor guidance\n- Student placement decisions\n- Performance prediction`,
	} as ApiOperationOptions,
};
