import { ApiOperationOptions } from '@nestjs/swagger';

export const AIThesisDocs = {
	checkDuplicate: {
		summary: 'Check thesis duplicates using AI',
		description: `Check for potential duplicate theses using AI-powered analysis.\n\n- **Moderator and Lecturer access** (requires authentication and MODERATOR or LECTURER role).\n- Analyzes the specified thesis against the database to find potential duplicates.\n- Uses AI algorithms to compare thesis content, titles, and abstracts.\n- Returns a list of potentially similar theses with similarity scores.\n- Helps moderators and lecturers identify plagiarism or highly similar research topics.\n- Logs all duplicate check attempts and results.\n\n**Parameters:**\n- \`thesisId\`: Required - UUID of the thesis to check for duplicates.\n\n**Response includes:**\n- List of potentially duplicate theses\n- Similarity scores and matching criteria\n- Thesis information (title, abstract, author, etc.)\n- Confidence levels for each match\n\n**Use cases:**\n- Quality assurance during thesis review process\n- Plagiarism detection\n- Research topic overlap identification\n- Academic integrity enforcement\n- Lecturer supervision and guidance`,
	} as ApiOperationOptions,

	suggestThesesForGroup: {
		summary: 'Suggest theses for a group using AI',
		description: `Get AI-powered suggestions for theses that would be suitable for the specified group.\n\n- **Authenticated access** (requires JWT authentication).\n- Analyzes group skills, responsibilities, project direction, and member capabilities.\n- Only suggests available theses (not selected by other groups).\n- Uses relevance scoring based on skill alignment and content matching.\n- Returns top 10 thesis suggestions by default with relevance scores.\n- Considers group size and complexity requirements.\n\n**Parameters:**\n- \`groupId\`: Required - UUID of the group to suggest theses for.\n\n**Response includes:**\n- List of suggested theses with relevance scores\n- Thesis information (title, description, lecturer)\n- Matching factors and alignment analysis\n- Relevance breakdown and recommendations\n\n**Algorithm factors:**\n- Content similarity: Text matching between thesis and group direction\n- Skill relevance: How well thesis requirements match group skills\n- Complexity alignment: Thesis complexity vs group size and capabilities\n- Lecturer expertise: Alignment with group domain and interests\n\n**Use cases:**\n- Thesis selection assistance\n- Project-group matching\n- Academic planning and guidance\n- Research direction alignment\n- Workload balancing for groups`,
	} as ApiOperationOptions,
};
